### ISSUE TITLE
module path "go.bug.st/downloader/v2" does not work

### ISSUE THREAD

**Issue by mlausch1963** [bugst/go-downloader#7]
The module has "module go.bug.st/downloader/v2" in it's go.mod file.
This URL does not resolve to a valid golang module, github returns with a 404 error

![image](https://user-images.githubusercontent.com/8876611/115016376-3d523900-9eb5-11eb-98f6-585fcfe687bb.png)

**Comment by cmaglie** [comment]
Sorry for the long delay, for some reason this issue went off my radar, the problem should be fixed now.

Amazingly, in my local system, everything is working fine even before the fix...

**Comment by mlausch1963** [comment]
Maybe, because you had a local copy in your GO directory. Then the compiler does not contact the remote git server.

**Comment by cmaglie** [comment]
I tried to clean up `$GOPATH/pkg/mod/` and `$GOPATH/src` but no luck...
The only way to actually force a re-download seems to be to specify a branch like:
```
go get go.bug.st/downloader/v2@master
```
Only in this case `go get` will try to check for updates.
